#!/bin/bash

# This is a helper script, wraps any command and sets up environment for
# autossl.so.
# Autossl.so is an LD_PRELOAD-ed library which intercepts network connections
# and upgrade them to TLS.
#
# This helper script provides convenience logic to help you type less when
# using it with common simple commands, like "wget <URL>". You probably
# use it only with simple commands anyways, so this convenience logic is
# opt-out. Turn it off by set AUTOSSL_CONVENIENCE=off in your invoking
# environment.
# 
# As part of the convenience it (1) replaces https url-like command line
# arguments to http (to let autossl.so intercept the plain connection and
# upgrade it back to https during the connection) and (2) find domain
# names in command line arguments and passes appropriate "-servername"
# parameter to the underlaying openssl command.
# 
# Set OPENSSL_EXTRA_ARGS environment variable to pass more parameters to openssl.
# 
# It has an embedding port mapping which contains common plain:tls port
# pairs for a given protocol, but you can extend it by setting splace
# separated "plain:tls" port number pairs in AUTOSSL_TLS_PORT_MAP env
# variable.
# 
# See autossl.so docs for more info.

help()
{
	echo "Usage: autossl <COMMAND> [<ARGUMENTS>]"
	echo "Environment:"
	echo "  AUTOSSL_BACKEND - which program to use as a upgrade-to-TLS helper. supported: openssl (default), stunnel"
	echo "  AUTOSSL_CONVENIENCE - if set to \"off\", don't try to guess SNI servername"
	echo "  AUTOSSL_SILENT - less diagnostical messages"
	echo "  AUTOSSL_UPGRADE_PORTS - space-delimited list of port numbers which autossl should work on (default 80)"
	echo "  AUTOSSL_UPGRADE_IPS - space-delimited list of IPs which autossl should work on. unset means any."
	echo "  AUTOSSL_TLS_PORT_MAP - space-delimited list of colon-separated port number pairs denoting which port should be mapped to which one (some common ports defaulted)"
	echo "  OPENSSL_EXTRA_ARGS - additional options passed to openssl"
	echo "  STUNNEL_EXTRA_ARGS - additional options passed to stunnel"
}	

if [ $# = 0 ]
then
	help >&2
	exit -1
elif [ "$1" = --help ]
then
	help
	exit 0
else
	declare -a args
	servername=''
	
	if [ "$AUTOSSL_CONVENIENCE" = off ]
	then
		args=("$@")
	else
		for arg in "$@"
		do
			if [[ $arg =~ ^https://([^@/]*@)?([^/ :]+) ]]
			then
				servername=${BASH_REMATCH[2]}
			fi
			if [ "${arg:0:6}" = https: ]
			then
				arg=${arg/https:/http:}
			fi
			args+=("$arg")
		done
		
		if [ -n "$servername" ]
		then
			OPENSSL_EXTRA_ARGS="$OPENSSL_EXTRA_ARGS${OPENSSL_EXTRA_ARGS:+ }-servername $servername"
			export OPENSSL_EXTRA_ARGS
		fi
	fi
	
	if [ ! $AUTOSSL_SILENT ]
	then
		echo "autossl: run: ${args[@]}" >&2
	fi
	if [ $AUTOSSL_SILENT ]
	then
		OPENSSL_EXTRA_ARGS="$OPENSSL_EXTRA_ARGS${OPENSSL_EXTRA_ARGS:+ }-quiet"
	fi
	
	LD_PRELOAD=/usr/lib/tool/preload/autossl.so \
	AUTOSSL_UPGRADE_PORTS="80${AUTOSSL_UPGRADE_PORTS:+ }${AUTOSSL_UPGRADE_PORTS}" \
	AUTOSSL_TLS_CMD=autossl-conn \
	AUTOSSL_TLS_PORT_MAP="21:990 23:992 25:465 80:443 110:995 119:563 143:993 194:994 389:636 $AUTOSSL_TLS_PORT_MAP" \
	AUTOSSL_ERRNO=5 \
	exec "${args[@]}"
fi
